
package com.bookserviceapp.application;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookSOAPWebService", targetNamespace = "http://application.bookserviceapp.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookSOAPWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.bookserviceapp.application.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://application.bookserviceapp.com/", className = "com.bookserviceapp.application.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://application.bookserviceapp.com/", className = "com.bookserviceapp.application.GetAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.bookserviceapp.application.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookByTitle", targetNamespace = "http://application.bookserviceapp.com/", className = "com.bookserviceapp.application.GetBookByTitle")
    @ResponseWrapper(localName = "getBookByTitleResponse", targetNamespace = "http://application.bookserviceapp.com/", className = "com.bookserviceapp.application.GetBookByTitleResponse")
    public List<Book> getBookByTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "importBook", targetNamespace = "http://application.bookserviceapp.com/", className = "com.bookserviceapp.application.ImportBook")
    @ResponseWrapper(localName = "importBookResponse", targetNamespace = "http://application.bookserviceapp.com/", className = "com.bookserviceapp.application.ImportBookResponse")
    public void importBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

}
